#
# arch/xtensa/include/asm/Kbuild
#
# User exported xtensa header files

include include/asm-generic/Kbuild.asm

header-y += elf.h
header-y += user.h
header-y += coprocessor.h

#
# XTENSA-WORKAROUND:
#	Providing page.h for older buildroots for a while.
#
unifdef-y += page.h


